name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Release version if tests succeeded
  release:
    name: Publish
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
